export const phrases = {
    es: [
        { text: "La felicidad no es algo hecho. Viene de tus propias acciones.", author: "Dalai Lama" },
        { text: "Lo que no nos mata, nos hace más fuertes.", author: "Friedrich Nietzsche" },
        { text: "El único modo de hacer un gran trabajo es amar lo que haces.", author: "Steve Jobs" },
        { text: "No juzgues cada día por la cosecha que recoges, sino por las semillas que plantas.", author: "Robert Louis Stevenson" },
        { text: "La vida es lo que pasa mientras estás ocupado haciendo otros planes.", author: "John Lennon" },
        { text: "Pienso, luego existo.", author: "René Descartes" },
        { text: "La paciencia es amarga, pero su fruto es dulce.", author: "Jean-Jacques Rousseau" },
        { text: "El conocimiento es poder.", author: "Francis Bacon" },
        { text: "No busques los errores, busca un remedio.", author: "Henry Ford" },
        { text: "La calidad no es un acto, es un hábito.", author: "Aristóteles" },
        { text: "Tu tiempo es limitado, así que no lo desperdicies viviendo la vida de alguien más.", author: "Steve Jobs" },
        { text: "La mejor forma de predecir el futuro es creándolo.", author: "Peter Drucker" },
        { text: "Si quieres cambiar el mundo, cámbiate a ti mismo.", author: "Mahatma Gandhi" },
        { text: "No hay camino para la paz, la paz es el camino.", author: "Mahatma Gandhi" },
        { text: "La inteligencia sin ambición es un pájaro sin alas.", author: "Salvador Dalí" },
        { text: "El hombre nace libre, pero en todas partes está encadenado.", author: "Jean-Jacques Rousseau" },
        { text: "Solo sé que no sé nada.", author: "Sócrates" },
        { text: "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito.", author: "Aristóteles" },
        { text: "El que tiene un porqué para vivir puede soportar casi cualquier cómo.", author: "Friedrich Nietzsche" },
        { text: "La libertad está en ser dueños de nuestra propia vida.", author: "Platón" },
        { text: "El ignorante afirma, el sabio duda y reflexiona.", author: "Aristóteles" },
        { text: "No podemos enseñar nada a nadie; solo podemos ayudarles a que lo descubran por sí mismos.", author: "Galileo Galilei" },
        { text: "La vida es muy simple, pero insistimos en hacerla complicada.", author: "Confucio" },
        { text: "El éxito es ir de fracaso en fracaso sin perder el entusiasmo.", author: "Winston Churchill" },
        { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
        { text: "La mayor gloria no es nunca caer, sino levantarse siempre.", author: "Nelson Mandela" },
        { text: "El secreto de la felicidad no es hacer siempre lo que se quiere sino querer siempre lo que se hace.", author: "León Tolstói" },
        { text: "La imaginación es más importante que el conocimiento.", author: "Albert Einstein" },
        { text: "La vida es una tragedia cuando se ve en primer plano, pero una comedia en plano general.", author: "Charlie Chaplin" },
        { text: "Un hombre que no piensa por sí mismo no piensa en absoluto.", author: "Oscar Wilde" },
        { text: "Vivir es lo más raro del mundo. La mayoría de la gente existe, eso es todo.", author: "Oscar Wilde" },
        { text: "La verdad es que todo el mundo te va a hacer daño. Solo tienes que encontrar a aquellos por los que vale la pena sufrir.", author: "Bob Marley" },
        { text: "No dejes que el ruido de las opiniones ajenas silencie tu propia voz interior.", author: "Steve Jobs" },
        { text: "El destino se baraja las cartas, nosotros las jugamos.", author: "Arthur Schopenhauer" },
        { text: "Todo lo que somos es el resultado de lo que hemos pensado.", author: "Buda" },
        { text: "Cada mañana nacemos de nuevo. Lo que hacemos hoy es lo que más importa.", author: "Buda" },
        { text: "La paz viene de adentro. No la busques afuera.", author: "Buda" },
        { text: "Un viaje de mil millas comienza con un solo paso.", author: "Lao Tsé" },
        { text: "El sabio no dice todo lo que piensa, pero siempre piensa todo lo que dice.", author: "Aristóteles" },
        { text: "La música es una revelación más alta que toda la sabiduría y la filosofía.", author: "Ludwig van Beethoven" },
        { text: "No hay nada permanente excepto el cambio.", author: "Heráclito" },
        { text: "La brevedad es el alma del ingenio.", author: "William Shakespeare" },
        { text: "Aprender sin reflexionar es malgastar la energía.", author: "Confucio" },
        { text: "Elige un trabajo que te guste y no tendrás que trabajar ni un día de tu vida.", author: "Confucio" },
        { text: "Incluso la noche más oscura terminará y el sol saldrá.", author: "Victor Hugo" },
        { text: "La esperanza es el único bien común a todos los hombres; los que lo han perdido todo la poseen todavía.", author: "Tales de Mileto" },
        { text: "Nuestra mayor debilidad reside en rendirnos. La forma más segura de tener éxito es intentarlo una vez más.", author: "Thomas Edison" },
        { text: "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.", author: "Albert Schweitzer" },
        { text: "A veces la gente no quiere escuchar la verdad porque no quiere que sus ilusiones se vean destruidas.", author: "Friedrich Nietzsche" },
        { text: "El futuro pertenece a quienes creen en la belleza de sus sueños.", author: "Eleanor Roosevelt" },
        { text: "El que no vive para servir, no sirve para vivir.", author: "Teresa de Calcuta" },
        { text: "No busques el sentido de la vida, dáselo tú.", author: "Viktor Frankl" },
        { text: "En medio del invierno, aprendí por fin que había en mí un verano invencible.", author: "Albert Camus" },
        { text: "No vemos las cosas como son, sino como somos nosotros.", author: "Anaïs Nin" },
        { text: "El hombre es lo que lee.", author: "Joseph Brodsky" },
        { text: "La vida es una serie de colisiones con el futuro; no es la suma de lo que hemos sido, sino de lo que anhelamos ser.", author: "José Ortega y Gasset" },
        { text: "Vivir es nacer a cada instante.", author: "Erich Fromm" },
        { text: "El amor es la única respuesta cuerda y satisfactoria al problema de la existencia humana.", author: "Erich Fromm" },
        { text: "No tengas miedo de la perfección, nunca la alcanzarás.", author: "Salvador Dalí" },
        { text: "La muerte no es la mayor pérdida de la vida. La mayor pérdida es lo que muere dentro de nosotros mientras vivimos.", author: "Norman Cousins" },
        { text: "El hombre que no lee no tiene ninguna ventaja sobre el que no sabe leer.", author: "Mark Twain" },
        { text: "La vida comienza donde termina el miedo.", author: "Osho" },
        { text: "No hay nada como volver a un lugar que permanece sin cambios para encontrar las formas en las que tú mismo has cambiado.", author: "Nelson Mandela" },
        { text: "El verdadero viaje de descubrimiento no consiste en buscar nuevos paisajes, sino en tener nuevos ojos.", author: "Marcel Proust" },
        { text: "La felicidad no es un destino al que se llega, sino una forma de viajar.", author: "Margaret Lee Runbeck" },
        { text: "No podemos resolver problemas pensando de la misma manera que cuando los creamos.", author: "Albert Einstein" },
        { text: "El único error real es aquel del que no aprendemos nada.", author: "Henry Ford" },
        { text: "Haz hoy lo que otros no quieren, haz mañana lo que otros no pueden.", author: "Jerry Rice" },
        { text: "La disciplina es el puente entre las metas y los logros.", author: "Jim Rohn" },
        { text: "Tu vida no mejora por casualidad, mejora por el cambio.", author: "Jim Rohn" },
        { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
        { text: "No esperes. El momento nunca será el perfecto.", author: "Napoleon Hill" },
        { text: "Lo que la mente puede concebir y creer, la mente lo puede lograr.", author: "Napoleon Hill" },
        { text: "Nuestra vida es lo que nuestros pensamientos crean.", author: "Marco Aurelio" },
        { text: "La mejor venganza es ser diferente a quien causó el daño.", author: "Marco Aurelio" },
        { text: "Todo lo que escuchamos es una opinión, no un hecho. Todo lo que vemos es una perspectiva, no la verdad.", author: "Marco Aurelio" },
        { text: "Tienes poder sobre tu mente, no sobre los eventos externos. Siente esto y encontrarás la fuerza.", author: "Marco Aurelio" },
        { text: "La felicidad de tu vida depende de la calidad de tus pensamientos.", author: "Marco Aurelio" },
        { text: "Muy poco se necesita para tener una vida feliz; todo está dentro de ti mismo, en tu forma de pensar.", author: "Marco Aurelio" },
        { text: "Acepta las cosas a las que el destino te ata, y ama a las personas con las que el destino te trae, pero hazlo con todo tu corazón.", author: "Marco Aurelio" },
        { text: "No pierdas más tiempo discutiendo lo que debe ser un buen hombre. Sé uno.", author: "Marco Aurelio" },
        { text: "Si no es correcto, no lo hagas. Si no es verdad, no lo digas.", author: "Marco Aurelio" },
        { text: "El alma se tiñe del color de sus pensamientos.", author: "Marco Aurelio" },
        { text: "Estamos más a menudo asustados que heridos; y sufrimos más en la imaginación que en la realidad.", author: "Séneca" },
        { text: "No es que tengamos poco tiempo, es que perdemos mucho.", author: "Séneca" },
        { text: "Si un hombre no sabe a qué puerto navega, ningún viento es favorable.", author: "Séneca" },
        { text: "La suerte es lo que sucede cuando la preparación se encuentra con la oportunidad.", author: "Séneca" },
        { text: "El que es valiente es libre.", author: "Séneca" },
        { text: "Mientras vivimos, aprendamos a vivir.", author: "Séneca" },
        { text: "Asóciate con personas que te hagan mejor.", author: "Séneca" },
        { text: "La verdadera felicidad es disfrutar del presente sin ansiedad dependiente del futuro.", author: "Séneca" },
        { text: "Vivir significa luchar.", author: "Séneca" },
        { text: "No hay genio sin una mezcla de locura.", author: "Aristóteles" },
        { text: "El objetivo del arte es representar no la apariencia externa de las cosas, sino su significado interno.", author: "Aristóteles" },
        { text: "La amistad es una sola alma habitando en dos cuerpos.", author: "Aristóteles" },
        { text: "Cualquiera puede enfadarse, eso es algo muy sencillo. Pero enfadarse con la persona adecuada, en el grado exacto, en el momento oportuno, con el propósito justo y del modo correcto, eso, ciertamente, no resulta tan sencillo.", author: "Aristóteles" },
        { text: "La esperanza es el sueño del hombre despierto.", author: "Aristóteles" },
        { text: "Educar la mente sin educar el corazón no es educar en absoluto.", author: "Aristóteles" },
        { text: "La victoria tiene muchas madres, pero la derrota es huérfana.", author: "Aristóteles" },
        { text: "El sabio no busca el placer, sino la ausencia de dolor.", author: "Aristóteles" },
        { text: "El que ha superado sus miedos será verdaderamente libre.", author: "Aristóteles" },
        { text: "No dejes que lo que no puedes hacer interfiera con lo que puedes hacer.", author: "John Wooden" },
        { text: "El éxito no es final, el fracaso no es fatal: lo que cuenta es el valor para continuar.", author: "Winston Churchill" },
        { text: "Cree que puedes y ya habrás recorrido la mitad del camino.", author: "Theodore Roosevelt" },
        { text: "La única limitación de nuestros logros de mañana serán nuestras dudas de hoy.", author: "Franklin D. Roosevelt" },
        { text: "Siembra un pensamiento y cosecharás una acción; siembra una acción y cosecharás un hábito; siembra un hábito y cosecharás un carácter; siembra un carácter y cosecharás un destino.", author: "Samuel Smiles" },
        { text: "El primer paso para conseguir lo que quieres es tener el valor de deshacerte de lo que no quieres.", author: "Zig Ziglar" },
        { text: "Tu actitud, no tu aptitud, determinará tu altitud.", author: "Zig Ziglar" },
        { text: "Si puedes soñarlo, puedes hacerlo.", author: "Walt Disney" },
        { text: "La manera de empezar es dejar de hablar y empezar a hacer.", author: "Walt Disney" },
        { text: "La mayor aventura que puedes emprender es vivir la vida de tus sueños.", author: "Oprah Winfrey" },
        { text: "Conviértete en aquello que eres.", author: "Friedrich Nietzsche" },
        { text: "Sin música, la vida sería un error.", author: "Friedrich Nietzsche" },
        { text: "Quien tiene algo por qué vivir puede soportar cualquier cómo.", author: "Friedrich Nietzsche" },
        { text: "Hay que tener caos dentro de uno para dar a luz a una estrella que baila.", author: "Friedrich Nietzsche" },
        { text: "Aquel que lucha con monstruos debe tener cuidado de no convertirse en uno.", author: "Friedrich Nietzsche" },
        { text: "Lo que se hace por amor acontece siempre más allá del bien y del mal.", author: "Friedrich Nietzsche" },
        { text: "Solo los pensamientos que nos vienen caminando tienen valor.", author: "Friedrich Nietzsche" },
        { text: "El individuo ha luchado siempre para no ser absorbido por la tribu. Si lo intentas, a menudo estarás solo, y a veces asustado. Pero ningún precio es demasiado alto por el privilegio de ser uno mismo.", author: "Friedrich Nietzsche" },
        { text: "No hay hechos, solo interpretaciones.", author: "Friedrich Nietzsche" },
        { text: "La esperanza es en realidad el peor de los males, porque prolonga el tormento del hombre.", author: "Friedrich Nietzsche" },
        { text: "El hombre es una cuerda tendida entre el animal y el superhombre, una cuerda sobre un abismo.", author: "Friedrich Nietzsche" },
        { text: "La vida es un constante proceso de morir.", author: "Arthur Schopenhauer" },
        { text: "El destino es el que baraja las cartas, pero nosotros somos los que jugamos.", author: "Arthur Schopenhauer" },
        { text: "Cada hombre confunde los límites de su propio campo de visión con los límites del mundo.", author: "Arthur Schopenhauer" },
        { text: "La salud no lo es todo, pero sin ella, todo lo demás es nada.", author: "Arthur Schopenhauer" },
        { text: "Difícilmente se puede encontrar la felicidad dentro de uno mismo, pero es imposible encontrarla en cualquier otro lugar.", author: "Arthur Schopenhauer" },
        { text: "La soledad es la suerte de todos los espíritus excelentes.", author: "Arthur Schopenhauer" },
        { text: "El mundo es mi voluntad.", author: "Arthur Schopenhauer" },
        { text: "Toda verdad pasa por tres etapas. Primero, es ridiculizada. Segundo, es violentamente rechazada. Tercero, es aceptada como evidente por sí misma.", author: "Arthur Schopenhauer" },
        { text: "Estamos condenados a ser libres.", author: "Jean-Paul Sartre" },
        { text: "La existencia precede a la esencia.", author: "Jean-Paul Sartre" },
        { text: "El infierno son los otros.", author: "Jean-Paul Sartre" },
        { text: "Un hombre no es otra cosa que lo que hace de sí mismo.", author: "Jean-Paul Sartre" },
        { text: "Incluso si uno no hace nada, uno está eligiendo.", author: "Jean-Paul Sartre" },
        { text: "Todo ha sido descubierto, excepto cómo vivir.", author: "Jean-Paul Sartre" },
        { text: "Lo importante no es lo que han hecho de nosotros, sino lo que hacemos con lo que han hecho de nosotros.", author: "Jean-Paul Sartre" },
        { text: "Cada paso es una elección. Cada elección tiene sus consecuencias.", author: "Jean-Paul Sartre" },
        { text: "En medio del odio, descubrí que había, dentro de mí, un amor invencible.", author: "Albert Camus" },
        { text: "La libertad no es nada más que una oportunidad para ser mejor.", author: "Albert Camus" },
        { text: "Si el mundo fuera claro, el arte no existiría.", author: "Albert Camus" },
        { text: "El hombre es la única criatura que se niega a ser lo que es.", author: "Albert Camus" },
        { text: "La verdadera generosidad hacia el futuro consiste en entregarlo todo al presente.", author: "Albert Camus" },
        { text: "Aquéllos que escriben con claridad tienen lectores; aquéllos que escriben oscuramente tienen comentaristas.", author: "Albert Camus" },
        { text: "No camines delante de mí, puede que no te siga. No camines detrás de mí, puede que no te guíe. Camina a mi lado y sé mi amigo.", author: "Albert Camus" },
        { text: "Donde no hay esperanza, debemos inventarla.", author: "Albert Camus" },
        { text: "La duda es el principio de la sabiduría.", author: "Aristóteles" },
        { text: "Conócete a ti mismo.", author: "Sócrates" },
        { text: "Una vida no examinada no vale la pena vivirla.", author: "Sócrates" },
        { text: "Solo hay un bien: el conocimiento. Solo hay un mal: la ignorancia.", author: "Sócrates" },
        { text: "El orgullo divide a los hombres, la humildad los une.", author: "Sócrates" },
        { text: "Sé amable, pues cada persona con la que te cruzas está librando una ardua batalla.", author: "Platón" },
        { text: "La medida del hombre es lo que hace con el poder.", author: "Platón" },
        { text: "La música es para el alma lo que la gimnasia es para el cuerpo.", author: "Platón" },
        { text: "El comienzo es la parte más importante del trabajo.", author: "Platón" },
        { text: "Atreverse es perder el equilibrio momentáneamente. No atreverse es perderse a uno mismo.", author: "Søren Kierkegaard" },
        { text: "La vida debe ser vivida hacia adelante, pero solo puede ser entendida hacia atrás.", author: "Søren Kierkegaard" },
        { text: "La ansiedad es el vértigo de la libertad.", author: "Søren Kierkegaard" },
        { text: "El ser humano es una síntesis de lo temporal y lo eterno.", author: "Søren Kierkegaard" },
        { text: "Lo que me hace único es mi propia desesperación.", author: "Søren Kierkegaard" },
        { text: "La oración no cambia a Dios, sino que cambia a quien reza.", author: "Søren Kierkegaard" },
        { text: "Tan pronto como me etiquetas, me niegas.", author: "Søren Kierkegaard" },
        { text: "Lo más difícil es encontrarse a uno mismo.", author: "Søren Kierkegaard" },
        { text: "La fe es el salto al abismo.", author: "Søren Kierkegaard" },
        { text: "Dos cosas me llenan de admiración: el cielo estrellado fuera de mí y la ley moral dentro de mí.", author: "Immanuel Kant" },
        { text: "Obra de tal modo que la máxima de tu voluntad pueda valer siempre como principio de una legislación universal.", author: "Immanuel Kant" },
        { text: "Sapere aude: ¡Atrévete a saber!", author: "Immanuel Kant" },
        { text: "La paciencia es la fortaleza del débil y la impaciencia la debilidad del fuerte.", author: "Immanuel Kant" },
        { text: "Se mide la inteligencia de un individuo por la cantidad de incertidumbres que es capaz de soportar.", author: "Immanuel Kant" },
        { text: "La felicidad no es un ideal de la razón sino de la imaginación.", author: "Immanuel Kant" },
        { text: "El sabio puede cambiar de opinión. El necio, nunca.", author: "Immanuel Kant" },
        { text: "Vemos las cosas no como son, sino como somos.", author: "Immanuel Kant" },
        { text: "El hombre es lo que la educación hace de él.", author: "Immanuel Kant" },
        { text: "Si el hombre se hace a sí mismo un gusano, no debe quejarse cuando es pisoteado.", author: "Immanuel Kant" },
        { text: "El hombre es el único animal que debe trabajar.", author: "Immanuel Kant" },
        { text: "La libertad es aquella facultad que aumenta la utilidad de todas las demás facultades.", author: "Immanuel Kant" },
        { text: "Actúa siempre como si tus actos fueran a convertirse en una ley universal.", author: "Immanuel Kant" },
        { text: "Todo nuestro conocimiento comienza con los sentidos, procede luego al entendimiento y termina con la razón.", author: "Immanuel Kant" },
        { text: "Lo que es, es; lo que no es, no es.", author: "Parménides" },
        { text: "Nadie se baña dos veces en el mismo río.", author: "Heráclito" },
        { text: "El carácter es el destino.", author: "Heráclito" },
        { text: "Los ojos son mejores testigos que los oídos.", author: "Heráclito" },
        { text: "El sol es nuevo cada día.", author: "Heráclito" },
        { text: "Mucha instrucción no enseña a tener inteligencia.", author: "Heráclito" },
        { text: "La armonía invisible es mayor que la visible.", author: "Heráclito" },
        { text: "A la naturaleza le gusta ocultarse.", author: "Heráclito" },
        { text: "El pensamiento es una enfermedad sagrada.", author: "Heráclito" },
        { text: "La guerra es el padre de todas las cosas.", author: "Heráclito" },
        { text: "Todo fluye.", author: "Heráclito" },
        { text: "El tiempo es un niño que juega a los dados.", author: "Heráclito" },
        { text: "La ignorancia es la madre de todos los males.", author: "François Rabelais" },
        { text: "La verdadera sabiduría está en reconocer la propia ignorancia.", author: "Sócrates" },
        { text: "Prefiero sufrir una injusticia que cometerla.", author: "Sócrates" },
        { text: "Habla para que yo te conozca.", author: "Sócrates" },
        { text: "La belleza perece en la vida, pero es inmortal en el arte.", author: "Leonardo da Vinci" },
        { text: "Los detalles hacen la perfección, y la perfección no es un detalle.", author: "Leonardo da Vinci" },
        { text: "Nuestra vida se compone del tiempo de otros.", author: "Leonardo da Vinci" },
        { text: "El que no valora la vida no se la merece.", author: "Leonardo da Vinci" },
        { text: "Aquel que no castiga el mal, ordena que se haga.", author: "Leonardo da Vinci" },
        { text: "La simplicidad es la máxima sofisticación.", author: "Leonardo da Vinci" },
        { text: "Quien poco piensa, mucho yerra.", author: "Leonardo da Vinci" },
        { text: "La sabiduría es hija de la experiencia.", author: "Leonardo da Vinci" },
        { text: "Así como el hierro se oxida por la falta de uso, así la inacción destruye el intelecto.", author: "Leonardo da Vinci" },
        { text: "Todo nuestro conocimiento nos viene de las sensaciones.", author: "Leonardo da Vinci" },
        { text: "El arte nunca se termina, solo se abandona.", author: "Leonardo da Vinci" },
        { text: "El aprendizaje es lo único que la mente nunca agota, nunca teme y nunca lamenta.", author: "Leonardo da Vinci" },
        { text: "La primera regla es que no debes engañarte a ti mismo, y tú eres la persona más fácil de engañar.", author: "Richard Feynman" },
        { text: "En algún lugar, algo increíble está esperando ser descubierto.", author: "Carl Sagan" },
        { text: "La herida es el lugar por donde entra la luz.", author: "Rumi" },
        { text: "El que no ha sufrido lo que yo he sufrido, no sabe lo que yo sé.", author: "Proverbio Universal" },
        { text: "No es lo que te sucede, sino cómo reaccionas lo que importa.", author: "Epicteto" },
        { text: "El hombre sabio es aquel que no se duele por las cosas que no tiene, sino que se alegra por las que tiene.", author: "Epicteto" },
        { text: "Solo hay un camino hacia la felicidad y es dejar de preocuparse por las cosas que están más allá del poder de nuestra voluntad.", author: "Epicteto" },
        { text: "La sabiduría es el sol de las almas.", author: "Miguel de Unamuno" },
        { text: "Saber es poco, si no se sabe aplicar; tener ganas es poco, si no se hace.", author: "Goethe" },
        { text: "La belleza es verdad; la verdad, belleza.", author: "John Keats" },
        { text: "El hombre se descubre cuando se mide con un obstáculo.", author: "Antoine de Saint-Exupéry" },
        { text: "Lo que hace que el desierto sea hermoso es que en algún lugar esconde un pozo.", author: "Antoine de Saint-Exupéry" },
        { text: "El mundo es un libro y aquellos que no viajan leen solo una página.", author: "San Agustín" },
        { text: "Nuestra vida es lo que nuestros pensamientos crean.", author: "Marco Aurelio" },
        { text: "La mejor venganza es ser diferente a quien causó el daño.", author: "Marco Aurelio" },
        { text: "Todo lo que escuchamos es una opinión, no un hecho.", author: "Marco Aurelio" },
        { text: "Toda nuestra ciencia, comparada con la realidad, es primitiva y pueril... y sin embargo, es lo más valioso que tenemos.", author: "Albert Einstein" },
        { text: "La medida de la inteligencia es la capacidad de cambiar.", author: "Albert Einstein" },
        { text: "No tengo talentos especiales, solo soy apasionadamente curioso.", author: "Albert Einstein" },
        { text: "La curiosidad es más importante que la inteligencia.", author: "Albert Einstein" },
        { text: "Si no puedes explicarlo de forma sencilla, no lo entiendes lo suficientemente bien.", author: "Albert Einstein" },
        { text: "Dos cosas son infinitas: el universo y la estupidez humana; y yo no estoy tan seguro del universo.", author: "Albert Einstein" },
        { text: "No podemos resolver problemas pensando de la misma manera que cuando los creamos.", author: "Albert Einstein" },
        { text: "La felicidad no es algo que se pospone para el futuro; es algo que se diseña para el presente.", author: "Jim Rohn" },
        { text: "Las dificultades a menudo preparan a la gente común para un destino extraordinario.", author: "C.S. Lewis" },
        { text: "No hay nada como un sueño para crear el futuro.", author: "Victor Hugo" },
        { text: "Para ser irremplazable, uno siempre debe ser diferente.", author: "Coco Chanel" },
        { text: "Haz de cada día tu obra maestra.", author: "John Wooden" },
        { text: "Todo esfuerzo es un éxito, incluso si no logras tu objetivo.", author: "Desconocido" },
        { text: "Sé tú mismo; los demás puestos ya están ocupados.", author: "Oscar Wilde" },
        { text: "El corazón tiene razones que la razón no entiende.", author: "Blaise Pascal" },
        { text: "La duda es uno de los nombres de la inteligencia.", author: "Jorge Luis Borges" },
        { text: "Cualquier destino, por largo y complicado que sea, consta en realidad de un solo momento: el momento en que el hombre sabe para siempre quién es.", author: "Jorge Luis Borges" },
        { text: "No somos responsables de las emociones, pero sí de lo que hacemos con ellas.", author: "Jorge Bucay" },
        { text: "El que lee mucho y anda mucho, ve mucho y sabe mucho.", author: "Miguel de Cervantes" },
        { text: "Confía en el tiempo, que suele dar dulces salidas a muchas amargas dificultades.", author: "Miguel de Cervantes" },
        { text: "La pluma es la lengua del alma.", author: "Miguel de Cervantes" },
        { text: "Nada es tan difícil que no se pueda conseguir con la perseverancia.", author: "Erasmo de Rotterdam" },
        { text: "El hombre es un animal racional que siempre pierde la cabeza cuando tiene que actuar racionalmente.", author: "Oscar Wilde" },
        { text: "La experiencia no es lo que te sucede, es lo que haces con lo que te sucede.", author: "Aldous Huxley" },
        { text: "A veces, incluso vivir es un acto de coraje.", author: "Séneca" },
        { text: "La brevedad es el alma del ingenio.", author: "William Shakespeare" },
        { text: "Sabemos lo que somos, pero no lo que podemos llegar a ser.", author: "William Shakespeare" },
        { text: "El mundo no está en peligro por las malas personas sino por aquellas que permiten la maldad.", author: "Albert Einstein" },
        { text: "La vida es una obra de teatro que no admite ensayos.", author: "Charlie Chaplin" },
        { text: "Mirar atrás es una forma de morir.", author: "Gilles Deleuze" },
        { text: "La inteligencia es la habilidad de adaptarse al cambio.", author: "Stephen Hawking" },
        { text: "El mayor enemigo del conocimiento no es la ignorancia, es la ilusión del conocimiento.", author: "Stephen Hawking" },
        { text: "No importa lo lenta que sea tu progresión, siempre vas más rápido que el que no lo intenta.", author: "Desconocido" },
        { text: "No hay camino para la verdad, la verdad es el camino.", author: "Mahatma Gandhi" },
        { text: "El que domina a los otros es fuerte; el que se domina a sí mismo es poderoso.", author: "Lao Tsé" },
        { text: "El conocimiento habla, pero la sabiduría escucha.", author: "Jimi Hendrix" },
        { text: "Piensa como un hombre de acción, actúa como un hombre de pensamiento.", author: "Henri Bergson" },
        { text: "La vida es un experimento en el que puedes fallar, pero nunca dejar de aprender.", author: "Ralph Waldo Emerson" },
        { text: "La libertad consiste en ser dueños de nuestra propia vida.", author: "Platón" },
        { text: "El único verdadero viaje de descubrimiento consiste no en buscar nuevos paisajes, sino en mirar con nuevos ojos.", author: "Marcel Proust" },
        { text: "Nunca es demasiado tarde para ser lo que podrías haber sido.", author: "George Eliot" },
        { text: "El valor no es la ausencia de miedo, sino la fortaleza de seguir adelante a pesar del miedo.", author: "Paulo Coelho" },
        { text: "Solo en la tranquilidad de la mente podemos ver la realidad.", author: "Buda" },
        { text: "La felicidad no depende de lo que tienes o de quién eres, depende únicamente de lo que piensas.", author: "Buda" },
        { text: "Una mente negativa nunca te dará una vida positiva.", author: "Desconocido" },
        { text: "Lo que somos hoy descansa en lo que pensamos ayer, y nuestros pensamientos actuales forjan nuestra vida futura.", author: "Buda" },
        { text: "No reces por una vida fácil, reza por la fuerza para soportar una difícil.", author: "Bruce Lee" },
        { text: "El obstáculo es el camino.", author: "Marco Aurelio" },
        { text: "El mundo rompe a todos, y después, algunos son fuertes en los lugares rotos.", author: "Ernest Hemingway" },
        { text: "El dolor es inevitable, el sufrimiento es opcional.", author: "Buda" },
        { text: "No podemos elegir nuestras circunstancias externas, pero siempre podemos elegir cómo responder a ellas.", author: "Epicteto" },
        { text: "Sé tú mismo, los demás puestos ya están ocupados.", author: "Oscar Wilde" },
        { text: "Si buscas resultados distintos, no hagas siempre lo mismo.", author: "Albert Einstein" },
        { text: "La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.", author: "Charles R. Swindoll" },
        { text: "Todo parece imposible hasta que se hace.", author: "Nelson Mandela" },
        { text: "Da siempre lo mejor de ti. Lo que plantes ahora, lo cosecharás más tarde.", author: "Og Mandino" },
        { text: "La paciencia no es simplemente la capacidad de esperar, es cómo nos comportamos mientras esperamos.", author: "Joyce Meyer" },
        { text: "El éxito es la suma de pequeños esfuerzos repetidos día tras día.", author: "Robert Collier" },
        { text: "No dejes que el ayer ocupe demasiado del hoy.", author: "Will Rogers" },
        { text: "No cuentes los días, haz que los días cuenten.", author: "Muhammad Ali" },
        { text: "Cada santo tiene un pasado y cada pecador tiene un futuro.", author: "Oscar Wilde" },
        { text: "La educación es el arma más poderosa que puedes usar para cambiar el mundo.", author: "Nelson Mandela" },
        { text: "La mejor manera de encontrarte a ti mismo es perderte en el servicio a los demás.", author: "Mahatma Gandhi" },
        { text: "Solo hay una felicidad en esta vida: amar y ser amado.", author: "George Sand" },
        { text: "No midas tu riqueza por el dinero que tienes, mídela por aquellas cosas que no cambiarías por dinero.", author: "Paulo Coelho" },
        { text: "El fracaso es solo la oportunidad de comenzar de nuevo de forma más inteligente.", author: "Henry Ford" },
        { text: "Haz lo que puedas, con lo que tengas, donde estés.", author: "Theodore Roosevelt" },
        { text: "A veces, la decisión más pequeña puede cambiar tu vida para siempre.", author: "Keri Russell" },
        { text: "La imaginación lo es todo. Es la vista previa de las próximas atracciones de la vida.", author: "Albert Einstein" },
        { text: "La mente es todo. Te conviertes en lo que crees.", author: "Buda" },
        { text: "Los grandes pensamientos hablan solo a la mente pensante, pero las grandes acciones hablan a toda la humanidad.", author: "Theodore Roosevelt" },
        { text: "Solo soy un hombre, pero soy un hombre. No puedo hacerlo todo, pero puedo hacer algo.", author: "Edward Everett Hale" },
        { text: "Mantén tus ojos en las estrellas y tus pies en el suelo.", author: "Theodore Roosevelt" },
        { text: "La mayor gloria no es nunca caer, sino levantarse cada vez que caemos.", author: "Confucio" },
        { text: "No esperes a que las condiciones sean perfectas para empezar, el inicio hace las condiciones perfectas.", author: "Alan Cohen" },
        { text: "Cree que puedes y estarás a medio camino.", author: "Theodore Roosevelt" },
        { text: "El secreto para salir adelante es empezar.", author: "Mark Twain" },
        { text: "No hay atajos para cualquier lugar que merezca la pena ir.", author: "Beverly Sills" },
        { text: "El hombre que mueve una montaña comienza llevándose piedras pequeñas.", author: "Confucio" },
        { text: "Un viaje de mil millas comienza con un solo paso.", author: "Lao Tsé" },
        { text: "Si no nosotros, ¿quién? Si no ahora, ¿cuándo?", author: "John F. Kennedy" },
        { text: "El coraje es la primera de las cualidades humanas porque es la que garantiza todas las demás.", author: "Winston Churchill" },
        { text: "Acepta la responsabilidad de tu vida. Date cuenta de que eres tú quien te llevará a donde quieres ir, nadie más.", author: "Les Brown" }
    ],
    en: [
        { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
        { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
        { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
        { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
        { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
        { text: "I think, therefore I am.", author: "René Descartes" },
        { text: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau" },
        { text: "Knowledge is power.", author: "Francis Bacon" },
        { text: "Don't find fault, find a remedy.", author: "Henry Ford" },
        { text: "Quality is not an act, it is a habit.", author: "Aristotle" },
        { text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
        { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
        { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
        { text: "There is no way to peace, peace is the way.", author: "Mahatma Gandhi" },
        { text: "Intelligence without ambition is a bird without wings.", author: "Salvador Dalí" },
        { text: "Man is born free, and everywhere he is in chains.", author: "Jean-Jacques Rousseau" },
        { text: "I know that I know nothing.", author: "Socrates" },
        { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
        { text: "He who has a why to live for can bear almost any how.", author: "Friedrich Nietzsche" },
        { text: "Freedom is being masters of our own lives.", author: "Plato" },
        { text: "The ignorant affirm, the wise doubt and reflect.", author: "Aristotle" },
        { text: "We cannot teach people anything; we can only help them discover it within themselves.", author: "Galileo Galilei" },
        { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
        { text: "Success is going from failure to failure without losing enthusiasm.", author: "Winston Churchill" },
        { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
        { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
        { text: "The secret of happiness is not in doing what one likes, but in liking what one does.", author: "Leo Tolstoy" },
        { text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
        { text: "Life is a tragedy when seen in close-up, but a comedy in long-shot.", author: "Charlie Chaplin" },
        { text: "A man who does not think for himself does not think at all.", author: "Oscar Wilde" },
        { text: "To live is the rarest thing in the world. Most people exist, that is all.", author: "Oscar Wilde" },
        { text: "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.", author: "Bob Marley" },
        { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs" },
        { text: "Fate shuffles the cards, and we play them.", author: "Arthur Schopenhauer" },
        { text: "All that we are is the result of what we have thought.", author: "Buddha" },
        { text: "Each morning we are born again. What we do today is what matters most.", author: "Buddha" },
        { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
        { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
        { text: "The wise man does not say all that he thinks, but he always thinks all that he says.", author: "Aristotle" },
        { text: "Music is a higher revelation than all wisdom and philosophy.", author: "Ludwig van Beethoven" },
        { text: "There is nothing permanent except change.", author: "Heraclitus" },
        { text: "Brevity is the soul of wit.", author: "William Shakespeare" },
        { text: "Learning without reflection is a waste of energy.", author: "Confucius" },
        { text: "Choose a job you love, and you will never have to work a day in your life.", author: "Confucius" },
        { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo" },
        { text: "Hope is the only good common to all men; those who have nothing else possess it still.", author: "Thales" },
        { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison" },
        { text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
        { text: "Sometimes people don't want to hear the truth because they don't want their illusions destroyed.", author: "Friedrich Nietzsche" },
        { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
        { text: "The first principle is that you must not fool yourself, and you are the easiest person to fool.", author: "Richard Feynman" },
        { text: "Somewhere, something incredible is waiting to be known.", author: "Carl Sagan" },
        { text: "The wound is the place where the Light enters you.", author: "Rumi" },
        { text: "He who has not suffered what I have suffered, does not know what I know.", author: "Universal Proverb" },
        { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
        { text: "A wise man is he who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus" },
        { text: "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.", author: "Epictetus" },
        { text: "Wisdom is the sun of souls.", author: "Miguel de Unamuno" },
        { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Goethe" },
        { text: "Beauty is truth, truth beauty.", author: "John Keats" },
        { text: "A man discovers himself when he measures himself against an obstacle.", author: "Antoine de Saint-Exupéry" },
        { text: "What makes the desert beautiful is that somewhere it hides a well.", author: "Antoine de Saint-Exupéry" },
        { text: "The world is a book and those who do not travel read only one page.", author: "St. Augustine" },
        { text: "Our life is what our thoughts make it.", author: "Marcus Aurelius" },
        { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
        { text: "Everything we hear is an opinion, not a fact.", author: "Marcus Aurelius" },
        { text: "All our science, measured against reality, is primitive and childlike... and yet it is the most precious thing we have.", author: "Albert Einstein" },
        { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
        { text: "I have no special talents. I am only passionately curious.", author: "Albert Einstein" },
        { text: "Curiosity is more important than intelligence.", author: "Albert Einstein" },
        { text: "If you can't explain it simply, you don't understand it well enough.", author: "Albert Einstein" },
        { text: "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.", author: "Albert Einstein" },
        { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
        { text: "Happiness is not something you postpone for the future; it is something you design for the present.", author: "Jim Rohn" },
        { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
        { text: "There is nothing like a dream to create the future.", author: "Victor Hugo" },
        { text: "In order to be irreplaceable one must always be different.", author: "Coco Chanel" },
        { text: "Make each day your masterpiece.", author: "John Wooden" },
        { text: "Every effort is a success, even if you don't reach your goal.", author: "Unknown" },
        { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
        { text: "The heart has its reasons which reason knows nothing of.", author: "Blaise Pascal" },
        { text: "Doubt is one of the names of intelligence.", author: "Jorge Luis Borges" },
        { text: "Any destiny, however long and complicated, consists in reality of a single moment: the moment in which a man knows forever who he is.", author: "Jorge Luis Borges" },
        { text: "We are not responsible for our emotions, but we are responsible for what we do with them.", author: "Jorge Bucay" },
        { text: "He who reads much and walks much, sees much and knows much.", author: "Miguel de Cervantes" },
        { text: "Trust time, which usually provides sweet escapes from many bitter difficulties.", author: "Miguel de Cervantes" },
        { text: "The pen is the tongue of the mind.", author: "Miguel de Cervantes" },
        { text: "Nothing is so difficult that it cannot be achieved with perseverance.", author: "Erasmus of Rotterdam" },
        { text: "Man is a rational animal who always loses his temper when he is called upon to act in accordance with the dictates of reason.", author: "Oscar Wilde" },
        { text: "Experience is not what happens to you; it's what you do with what happens to you.", author: "Aldous Huxley" },
        { text: "Sometimes even to live is an act of courage.", author: "Seneca" },
        { text: "Brevity is the soul of wit.", author: "William Shakespeare" },
        { text: "We know what we are, but know not what we may be.", author: "William Shakespeare" },
        { text: "The world is not in danger from bad people but from those who allow evil.", author: "Albert Einstein" },
        { text: "Life is a play that does not allow testing.", author: "Charlie Chaplin" },
        { text: "Looking back is a way of dying.", author: "Gilles Deleuze" },
        { text: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking" },
        { text: "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", author: "Stephen Hawking" },
        { text: "No matter how slow your progress is, you're still ahead of everyone who isn't trying.", author: "Unknown" },
        { text: "There is no path to truth, truth is the path.", author: "Mahatma Gandhi" },
        { text: "He who controls others may be powerful, but he who has mastered himself is mightier still.", author: "Lao Tzu" },
        { text: "Knowledge speaks, but wisdom listens.", author: "Jimi Hendrix" },
        { text: "Think like a man of action, act like a man of thought.", author: "Henri Bergson" },
        { text: "Life is an experiment in which you may fail, but never stop learning.", author: "Ralph Waldo Emerson" },
        { text: "Freedom is being masters of our own lives.", author: "Plato" },
        { text: "The only real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", author: "Marcel Proust" },
        { text: "It is never too late to be what you might have been.", author: "George Eliot" },
        { text: "Courage is not the absence of fear, but the strength to keep going despite the fear.", author: "Paulo Coelho" },
        { text: "Only in the stillness of the mind can we see reality.", author: "Buddha" },
        { text: "Happiness does not depend on what you have or who you are, it solely relies on what you think.", author: "Buddha" },
        { text: "A negative mind will never give you a positive life.", author: "Unknown" },
        { text: "What we are today comes from our thoughts of yesterday, and our present thoughts build our life of tomorrow.", author: "Buddha" },
        { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
        { text: "The obstacle is the way.", author: "Marcus Aurelius" },
        { text: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway" },
        { text: "Pain is inevitable, suffering is optional.", author: "Buddha" },
        { text: "We cannot choose our external circumstances, but we can always choose how we respond to them.", author: "Epictetus" },
        { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
        { text: "If you want different results, do not do the same things.", author: "Albert Einstein" },
        { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
        { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
        { text: "Always do your best. What you plant now, you will harvest later.", author: "Og Mandino" },
        { text: "Patience is not simply the ability to wait - it's how we behave while we're waiting.", author: "Joyce Meyer" },
        { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
        { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
        { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
        { text: "Every saint has a past, and every sinner has a future.", author: "Oscar Wilde" },
        { text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela" },
        { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
        { text: "There is only one happiness in this life, to love and be loved.", author: "George Sand" },
        { text: "Do not measure your wealth by the money you have, measure it by the things you would not trade for money.", author: "Paulo Coelho" },
        { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
        { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
        { text: "Sometimes the smallest decision can change your life forever.", author: "Keri Russell" },
        { text: "Imagination is everything. It is the preview of life's coming attractions.", author: "Albert Einstein" },
        { text: "The mind is everything. What you think you become.", author: "Buddha" },
        { text: "Great thoughts speak only to the thoughtful mind, but great actions speak to all mankind.", author: "Theodore Roosevelt" },
        { text: "I am only one, but I am one. I cannot do everything, but I can do something.", author: "Edward Everett Hale" },
        { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
        { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
        { text: "Don't wait for conditions to be perfect to begin, beginning makes the conditions perfect.", author: "Alan Cohen" },
        { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
        { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
        { text: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
        { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
        { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
        { text: "If not us, who? If not now, when?", author: "John F. Kennedy" },
        { text: "Courage is rightly esteemed the first of human qualities because it is the quality which guarantees all others.", author: "Winston Churchill" },
        { text: "Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.", author: "Les Brown" }
    ]
};
