export const PHILOSOPHICAL_QUOTES = [
    "La primera y mejor victoria es conquistarse a uno mismo. - Platón",
    "Somos lo que hacemos repetidamente. La excelencia, entonces, no es un acto, sino un hábito. - Aristóteles",
    "No es que tengamos poco tiempo, sino que perdemos mucho. - Séneca",
    "El hombre que mueve montañas comienza apartando piedrecitas. - Confucio",
    "La felicidad depende de nosotros mismos. - Aristóteles",
    "El secreto de avanzar es empezar. - Mark Twain",
    "El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier",
    "Todo lo que somos es el resultado de lo que hemos pensado. - Buda",
    "Si dominas tu mente, dominas tu mundo. - Siddhārtha Gautama",
    "El que tiene un porqué para vivir puede soportar casi cualquier cómo. - Friedrich Nietzsche",
    "Sólo yo puedo cambiar mi vida. Nadie puede hacerlo por mí. - Carol Burnett",
    "Actúa o acepta. - Anónimo",
    "Haz lo que puedas, con lo que tengas, donde estés. - Theodore Roosevelt",
    "El único límite a nuestros logros de mañana serán nuestras dudas de hoy. - Franklin D. Roosevelt",
    "La disciplina es el puente entre las metas y los logros. - Jim Rohn",
    "La paciencia es amarga, pero su fruto es dulce. - Jean-Jacques Rousseau",
    "La vida es un eco. Si no te gusta lo que estás recibiendo, fíjate en lo que estás emitiendo. - Anónimo",
    "Cree que puedes y estarás a mitad del camino. - Theodore Roosevelt",
    "La motivación nos impulsa a comenzar, el hábito nos permite continuar. - Jim Ryun",
    "Aquel que conquista a otros es fuerte; aquel que se conquista a sí mismo es poderoso. - Lao Tsé",
    "La mente lo es todo. Te conviertes en lo que crees. - Buda",
    "Nuestra mayor gloria no está en no caer nunca, sino en levantarnos cada vez que caemos. - Confucio",
    "La acción es la clave fundamental de todo éxito. - Pablo Picasso",
    "Tus hábitos determinan tu futuro. - Jack Canfield",
    "No cuentes los días, haz que los días cuenten. - Muhammad Ali",
    "Poco a poco, uno camina muy lejos. - Proverbio",
    "Para entenderlo todo, es necesario olvidarlo todo. - Osho",
    "No reces por una vida fácil, reza para ser una persona fuerte. - Bruce Lee",
    "Las dificultades a menudo preparan a la gente común para un destino extraordinario. - C.S. Lewis",
    "Da siempre lo mejor de ti. Lo que plantes ahora, lo cosecharás más tarde. - Og Mandino",
    "Tu tiempo es limitado, no lo desperdicies viviendo la vida de otro. - Steve Jobs",
    "No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas. - Jack Canfield",
    "La clave de la vida es la constancia. - Anónimo",
    "No te detengas cuando estés cansado, detente cuando hayas terminado. - Marilyn Monroe",
    "Cada mañana nacemos de nuevo. Lo que hacemos hoy es lo que más importa. - Buda",
    "Me tomó quince años de arduo trabajo tener éxito de la noche a la mañana. - Lionel Messi",
    "El dolor es temporal, la gloria es eterna. - George S. Patton",
    "A veces, la adversidad es lo que necesitas enfrentar para ser exitoso. - Zig Ziglar",
    "La manera de empezar es dejar de hablar y empezar a hacer. - Walt Disney",
    "Incluso el viaje más largo comienza con un solo paso. - Lao Tsé",
    "La vida empieza al final de tu zona de confort. - Neale Donald Walsch",
    "Si no estás dispuesto a arriesgar lo inusual, tendrás que conformarte con lo ordinario. - Jim Rohn",
    "El único lugar donde el éxito viene antes que el trabajo es en el diccionario. - Vidal Sassoon",
    "No limites tus desafíos, desafía tus límites. - Anónimo",
    "Caerse es un accidente; quedarse en el suelo es una elección. - Anónimo",
    "Nunca es demasiado tarde para ser lo que podrías haber sido. - George Eliot",
    "Toma la decisión de ser grande, de lo contrario, nunca lo serás. - Anónimo",
    "El carácter se forja en los pequeños detalles. - Anónimo",
    "La voluntad es el único músculo que se hace más fuerte con la fatiga. - Anónimo",
    "Es duro fracasar, pero es todavía peor no haber intentado nunca triunfar. - Theodore Roosevelt"
];
